Repository thensel23/collaborate, pull requests merged in 2023-03, with the labels that each got.

#3 Added the data files
  unit1/data/efield.t
  unit1/data/expec.t
  unit1/data/npop.t
  unit1/data/nstate_i.t
  unit1/data/table.dat
Labels: bug

#5 Done some work on task 1
  unit1/src/notebook_unit1.ipynb
Labels: enhancement

#4 task 1 numerical analysis
  data/efield.t
  data/expec.t
  data/npop.t
  data/nstate_i.t
  data/table.dat
  unit1/src/notebook_unit1.ipynb
Labels: good first issue

#13 Timo started with working on the numerical task
  our_package/data_handling.py
  our_package/main.py
Labels: enhancement

#26 First tests written for analysis.py
  our_package/test/test_analysis.py
Labels: enhancement
